// <auto-generated />
using CodeFirst;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CodeFirst.Migrations
{
    [DbContext(typeof(CodeFirstDBContext))]
    [Migration("20221113025130_AddNewDb")]
    partial class AddNewDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CodeFirst.Models.AddItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DetailProduk")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Harga")
                        .HasColumnType("integer");

                    b.Property<string>("NamaProduk")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StokProduk")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AddItem");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DetailProduk = "Detail1",
                            Harga = 1000,
                            NamaProduk = "produk1",
                            StokProduk = 1
                        },
                        new
                        {
                            Id = 2,
                            DetailProduk = "Detail2",
                            Harga = 2000,
                            NamaProduk = "produk2",
                            StokProduk = 2
                        },
                        new
                        {
                            Id = 3,
                            DetailProduk = "Detail3",
                            Harga = 3000,
                            NamaProduk = "produk3",
                            StokProduk = 3
                        });
                });

            modelBuilder.Entity("CodeFirst.Models.Checkout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alamat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Harga")
                        .HasColumnType("double precision");

                    b.Property<double>("HargaOngkir")
                        .HasColumnType("double precision");

                    b.Property<int>("JumlahProduk")
                        .HasColumnType("integer");

                    b.Property<string>("Lokasi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamaProduk")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamaToko")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("SubTotal")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalTagihan")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Checkout");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alamat = "alamat1",
                            Harga = 1000.0,
                            HargaOngkir = 9000.0,
                            JumlahProduk = 1,
                            Lokasi = "lokasi1",
                            NamaProduk = "produk1",
                            NamaToko = "toko1",
                            SubTotal = 1000.0,
                            TotalTagihan = 10000.0
                        },
                        new
                        {
                            Id = 2,
                            Alamat = "alamat2",
                            Harga = 2000.0,
                            HargaOngkir = 9000.0,
                            JumlahProduk = 2,
                            Lokasi = "lokasi2",
                            NamaProduk = "produk2",
                            NamaToko = "toko2",
                            SubTotal = 4000.0,
                            TotalTagihan = 13000.0
                        },
                        new
                        {
                            Id = 3,
                            Alamat = "alamat3",
                            Harga = 3000.0,
                            HargaOngkir = 9000.0,
                            JumlahProduk = 3,
                            Lokasi = "lokasi3",
                            NamaProduk = "produk3",
                            NamaToko = "toko3",
                            SubTotal = 9000.0,
                            TotalTagihan = 18000.0
                        });
                });

            modelBuilder.Entity("CodeFirst.Models.DaftarTransaksi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PenggunaId")
                        .HasColumnType("integer");

                    b.Property<int>("ProdukId")
                        .HasColumnType("integer");

                    b.Property<string>("StatusTransaksi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TotalTagihan")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("PenggunaId");

                    b.HasIndex("ProdukId");

                    b.ToTable("DaftarTransaksi");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PenggunaId = 1,
                            ProdukId = 1,
                            StatusTransaksi = "berhasil",
                            TotalTagihan = 10000.0
                        },
                        new
                        {
                            Id = 2,
                            PenggunaId = 2,
                            ProdukId = 2,
                            StatusTransaksi = "gagal",
                            TotalTagihan = 13000.0
                        },
                        new
                        {
                            Id = 3,
                            PenggunaId = 3,
                            ProdukId = 3,
                            StatusTransaksi = "berhasil",
                            TotalTagihan = 19000.0
                        });
                });

            modelBuilder.Entity("CodeFirst.Models.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Buah")
                        .HasColumnType("boolean");

                    b.Property<bool>("Sayur")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Kategori");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Buah = true,
                            Sayur = false
                        },
                        new
                        {
                            Id = 2,
                            Buah = false,
                            Sayur = true
                        },
                        new
                        {
                            Id = 3,
                            Buah = true,
                            Sayur = false
                        });
                });

            modelBuilder.Entity("CodeFirst.Models.Keranjang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Harga")
                        .HasColumnType("double precision");

                    b.Property<string>("Lokasi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamaProduk")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamaToko")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("SubTotal")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalJumlah")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Keranjang");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Harga = 1000.0,
                            Lokasi = "lokasi1",
                            NamaProduk = "produk1",
                            NamaToko = "toko1",
                            SubTotal = 1000.0,
                            TotalJumlah = 1.0
                        },
                        new
                        {
                            Id = 2,
                            Harga = 2000.0,
                            Lokasi = "lokasi2",
                            NamaProduk = "produk2",
                            NamaToko = "toko2",
                            SubTotal = 4000.0,
                            TotalJumlah = 2.0
                        },
                        new
                        {
                            Id = 3,
                            Harga = 3000.0,
                            Lokasi = "lokasi3",
                            NamaProduk = "produk3",
                            NamaToko = "toko3",
                            SubTotal = 9000.0,
                            TotalJumlah = 3.0
                        });
                });

            modelBuilder.Entity("CodeFirst.Models.ListItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Harga")
                        .HasColumnType("double precision");

                    b.Property<string>("Lokasi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamaProduk")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ListItem");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Harga = 1000.0,
                            Lokasi = "lokasi1",
                            NamaProduk = "produk1"
                        },
                        new
                        {
                            Id = 2,
                            Harga = 2000.0,
                            Lokasi = "lokasi2",
                            NamaProduk = "produk2"
                        },
                        new
                        {
                            Id = 3,
                            Harga = 3000.0,
                            Lokasi = "lokasi3",
                            NamaProduk = "produk3"
                        });
                });

            modelBuilder.Entity("CodeFirst.Models.ListItemPenjual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Harga")
                        .HasColumnType("integer");

                    b.Property<string>("NamaProduk")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StokProduk")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ListItemPenjual");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Harga = 1000,
                            NamaProduk = "produk1",
                            StokProduk = 1
                        },
                        new
                        {
                            Id = 2,
                            Harga = 2000,
                            NamaProduk = "produk2",
                            StokProduk = 2
                        },
                        new
                        {
                            Id = 3,
                            Harga = 3000,
                            NamaProduk = "produk3",
                            StokProduk = 3
                        });
                });

            modelBuilder.Entity("CodeFirst.Models.Lokasi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Bantul")
                        .HasColumnType("boolean");

                    b.Property<bool>("DIY")
                        .HasColumnType("boolean");

                    b.Property<bool>("GunungKidul")
                        .HasColumnType("boolean");

                    b.Property<bool>("KulonProgo")
                        .HasColumnType("boolean");

                    b.Property<bool>("Sleman")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Lokasi");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bantul = false,
                            DIY = true,
                            GunungKidul = false,
                            KulonProgo = false,
                            Sleman = false
                        },
                        new
                        {
                            Id = 2,
                            Bantul = false,
                            DIY = false,
                            GunungKidul = false,
                            KulonProgo = false,
                            Sleman = true
                        },
                        new
                        {
                            Id = 3,
                            Bantul = true,
                            DIY = false,
                            GunungKidul = false,
                            KulonProgo = false,
                            Sleman = false
                        });
                });

            modelBuilder.Entity("CodeFirst.Models.Pembayaran", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("BankTransfer")
                        .HasColumnType("boolean");

                    b.Property<bool>("COD")
                        .HasColumnType("boolean");

                    b.Property<bool>("Mitra")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Pembayaran");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BankTransfer = true,
                            COD = false,
                            Mitra = false
                        },
                        new
                        {
                            Id = 2,
                            BankTransfer = false,
                            COD = true,
                            Mitra = true
                        },
                        new
                        {
                            Id = 3,
                            BankTransfer = false,
                            COD = false,
                            Mitra = true
                        });
                });

            modelBuilder.Entity("CodeFirst.Models.Pengguna", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("pengguna");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "user1@gmail.com",
                            Password = "pass1",
                            RoleId = 1,
                            Username = "user1"
                        },
                        new
                        {
                            Id = 2,
                            Email = "user2@gmail.com",
                            Password = "pass2",
                            RoleId = 1,
                            Username = "user2"
                        },
                        new
                        {
                            Id = 3,
                            Email = "user3@gmail.com",
                            Password = "pass3",
                            RoleId = 2,
                            Username = "user3"
                        });
                });

            modelBuilder.Entity("CodeFirst.Models.Pengiriman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Gosend")
                        .HasColumnType("boolean");

                    b.Property<bool>("Grab")
                        .HasColumnType("boolean");

                    b.Property<bool>("JNE")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Pengiriman");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Gosend = false,
                            Grab = true,
                            JNE = false
                        },
                        new
                        {
                            Id = 2,
                            Gosend = true,
                            Grab = false,
                            JNE = false
                        },
                        new
                        {
                            Id = 3,
                            Gosend = false,
                            Grab = false,
                            JNE = true
                        });
                });

            modelBuilder.Entity("CodeFirst.Models.PerItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DetailProduk")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Harga")
                        .HasColumnType("double precision");

                    b.Property<int>("JumlahProduk")
                        .HasColumnType("integer");

                    b.Property<string>("Lokasi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamaProduk")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamaToko")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("StokProduk")
                        .HasColumnType("integer");

                    b.Property<double>("SubTotal")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("PerItem");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DetailProduk = "DetailProduk1",
                            Harga = 1000.0,
                            JumlahProduk = 1,
                            Lokasi = "lokasi1",
                            NamaProduk = "produk1",
                            NamaToko = "toko1",
                            Rating = 1,
                            StokProduk = 1,
                            SubTotal = 1000.0
                        },
                        new
                        {
                            Id = 2,
                            DetailProduk = "DetailProduk2",
                            Harga = 2000.0,
                            JumlahProduk = 2,
                            Lokasi = "lokasi2",
                            NamaProduk = "produk2",
                            NamaToko = "toko2",
                            Rating = 2,
                            StokProduk = 2,
                            SubTotal = 4000.0
                        },
                        new
                        {
                            Id = 3,
                            DetailProduk = "DetailProduk3",
                            Harga = 3000.0,
                            JumlahProduk = 3,
                            Lokasi = "lokasi3",
                            NamaProduk = "produk3",
                            NamaToko = "toko3",
                            Rating = 3,
                            StokProduk = 3,
                            SubTotal = 9000.0
                        });
                });

            modelBuilder.Entity("CodeFirst.Models.Produk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Harga")
                        .HasColumnType("double precision");

                    b.Property<string>("Lokasi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamaProduk")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PenjualId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PenjualId");

                    b.ToTable("Produk");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Harga = 1000.0,
                            Lokasi = "lokasi1",
                            NamaProduk = "produk1",
                            PenjualId = 1
                        },
                        new
                        {
                            Id = 2,
                            Harga = 2000.0,
                            Lokasi = "lokasi2",
                            NamaProduk = "produk2",
                            PenjualId = 2
                        },
                        new
                        {
                            Id = 3,
                            Harga = 3000.0,
                            Lokasi = "lokasi3",
                            NamaProduk = "produk3",
                            PenjualId = 3
                        });
                });

            modelBuilder.Entity("CodeFirst.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pembeli"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Penjual"
                        });
                });

            modelBuilder.Entity("CodeFirst.Models.DaftarTransaksi", b =>
                {
                    b.HasOne("CodeFirst.Models.Pengguna", "Pengguna")
                        .WithMany()
                        .HasForeignKey("PenggunaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeFirst.Models.ListItem", "ListItem")
                        .WithMany()
                        .HasForeignKey("ProdukId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ListItem");

                    b.Navigation("Pengguna");
                });

            modelBuilder.Entity("CodeFirst.Models.Pengguna", b =>
                {
                    b.HasOne("CodeFirst.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CodeFirst.Models.Produk", b =>
                {
                    b.HasOne("CodeFirst.Models.ListItem", "ListItem")
                        .WithMany()
                        .HasForeignKey("PenjualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ListItem");
                });
#pragma warning restore 612, 618
        }
    }
}
